export let geojson  = [
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.0747987, 28.4613816] },
      properties: {
        center_name: 'Max Hospital',
        district: 'Gurgaon',
        distance: 7,
        state: 'Haryana',
        fee_type: 'Paid',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.2137944, 28.535326] },
      properties: {
        center_name: 'Pt Madan Mohan Malviya Site 3',
        district: 'South Delhi',
        distance: 29,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.070629, 28.6322542] },
      properties: {
        center_name: 'Pt. Ma M Hospital DH S SITE 2',
        district: 'South Delhi',
        distance: 29,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.12991629999999, 28.4767912] },
      properties: {
        center_name: 'RAJKI BAL VIDHALY.AYA NAGAR S6',
        district: 'South Delhi',
        distance: 15,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.16599939999999, 28.5068854] },
      properties: {
        center_name: 'ILBS Session Site 4',
        district: 'South Delhi',
        distance: 21,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [76.73890519999999, 27.1686087] },
      properties: {
        center_name: '45 CHC PINAN BLOCK RENI',
        district: 'Alwar',
        distance: 212,
        state: 'Rajasthan',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.16599939999999, 28.5068854] },
      properties: {
        center_name: 'ILBS Session Site 3',
        district: 'South Delhi',
        distance: 21,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.16599939999999, 28.5068854] },
      properties: {
        center_name: 'ILBS Site 1',
        district: 'South Delhi',
        distance: 21,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.1248931, 28.5984847] },
      properties: {
        center_name: 'Delhi Cantt Gen Hosp. Site 2',
        district: 'New Delhi',
        distance: 26,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [76.6189162, 27.5879591] },
      properties: {
        center_name: 'HOMEOPATHI COLLEGE ShivajiPark',
        district: 'Alwar',
        distance: 152,
        state: 'Rajasthan',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.16599939999999, 28.5068854] },
      properties: {
        center_name: 'ILBS Session Site 2',
        district: 'South Delhi',
        distance: 21,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [76.73890519999999, 27.1686087] },
      properties: {
        center_name: '45 CHC RENI BLOCK RENI',
        district: 'Alwar',
        distance: 212,
        state: 'Rajasthan',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.1614627, 28.5214614] },
      properties: {
        center_name: 'Pratibha Vidyalaya Budhnagar C',
        district: 'New Delhi',
        distance: 22,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.1739149, 28.5793385] },
      properties: {
        center_name: 'Sarvodaya Co-ed Sch. Nanakpura',
        district: 'New Delhi',
        distance: 28,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.1089233, 28.5175383] },
      properties: {
        center_name: 'SKV Rajokari',
        district: 'New Delhi',
        distance: 15,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.08247639999999, 28.6095462] },
      properties: {
        center_name: 'Dada Dev Hospital DH',
        district: 'South West Delhi',
        distance: 25,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [76.9140943, 28.5947387] },
      properties: {
        center_name: 'Rao Tula Ram Hospital DH',
        district: 'South West Delhi',
        distance: 27,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [76.7587391, 27.2595369] },
      properties: {
        center_name: '45 CHC GADISAWAIRAM BLOCK RENI',
        district: 'Alwar',
        distance: 197,
        state: 'Rajasthan',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.08247639999999, 28.6095462] },
      properties: {
        center_name: 'Dada Dev Hospital 4',
        district: 'South West Delhi',
        distance: 25,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.1398317, 28.4901726] },
      properties: {
        center_name: 'SDMC Boys School MasoodPur',
        district: 'New Delhi',
        distance: 17,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.14790719999999, 28.6244326] },
      properties: {
        center_name: 'Shahid Captain Amit Verma Sch.',
        district: 'New Delhi',
        distance: 32,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.0682891, 28.5551891] },
      properties: {
        center_name: 'SDMC Boys Sch Shahbad Md.Pur',
        district: 'New Delhi',
        distance: 17,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.057636, 28.564051] },
      properties: {
        center_name: 'GCO-EDSSS DWARKA SEC II',
        district: 'South West Delhi',
        distance: 17,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.0881335, 28.586436] },
      properties: {
        center_name: 'SKV NO.2 PALAM VILLAGE',
        district: 'South West Delhi',
        distance: 22,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [76.9829161, 28.5478418] },
      properties: {
        center_name: 'GOVT. CO-ED SEC SCHOOL',
        district: 'South West Delhi',
        distance: 16,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.001637, 28.565885] },
      properties: {
        center_name: 'SKV CHHAWLA ID 1821026',
        district: 'South West Delhi',
        distance: 18,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.0309233, 28.5955409] },
      properties: {
        center_name: 'GOVT. CO-ED SV SECTOR13 DWARKA',
        district: 'South West Delhi',
        distance: 22,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.1001172, 28.6018934] },
      properties: {
        center_name: 'SKV NO. JANAKPURI ID 1618022',
        district: 'South West Delhi',
        distance: 25,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.05574779999999, 28.6449926] },
      properties: {
        center_name: 'GBSSS SHIV VIHAR ND ID1618267',
        district: 'South West Delhi',
        distance: 30,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.0075055, 28.5487158] },
      properties: {
        center_name: 'BSF CAMPUS CHAWLA',
        district: 'South West Delhi',
        distance: 15,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.06521099999999, 28.632436] },
      properties: {
        center_name: 'CGHS Vikaspuri PHC 1',
        district: 'South West Delhi',
        distance: 28,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.0774673, 28.6250012] },
      properties: {
        center_name: 'DGD Sadhnagar 1',
        district: 'South West Delhi',
        distance: 28,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.0511693, 28.5378483] },
      properties: {
        center_name: 'CHEST CLINIC BIJWASAN PHC 2',
        district: 'South West Delhi',
        distance: 13,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.080728, 28.628897] },
      properties: {
        center_name: 'MCW MAHENDRA PARK',
        district: 'South West Delhi',
        distance: 28,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.1084242, 28.6120307] },
      properties: {
        center_name: 'MCW Janak Puri PHC 1',
        district: 'South West Delhi',
        distance: 27,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.08911379999999, 28.6196007] },
      properties: {
        center_name: 'CGHS Janakpuri I PHC 1',
        district: 'South West Delhi',
        distance: 27,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.0456628, 28.6239314] },
      properties: {
        center_name: 'DGD Nawada PHC 1',
        district: 'South West Delhi',
        distance: 27,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.2010779, 28.6362404] },
      properties: {
        center_name: 'Atal Adarsh School Mandir Marg',
        district: 'New Delhi',
        distance: 38,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.1853308, 28.5603551] },
      properties: {
        center_name: 'Sarvodaya Co-ed RK Puram Sec 2',
        district: 'New Delhi',
        distance: 28,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.0858932, 28.5313637] },
      properties: {
        center_name: 'SBV Sr. Sec No.1 Samalkha',
        district: 'New Delhi',
        distance: 14,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.16423900000001, 28.494516] },
      properties: {
        center_name: 'SKV SCHOOL SULTANPUR S 3',
        district: 'South Delhi',
        distance: 20,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.0781057, 28.5750849] },
      properties: {
        center_name: 'SKV RAJ NAGAR-II ID 1821020',
        district: 'South West Delhi',
        distance: 20,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.2174596, 28.6365182] },
      properties: {
        center_name: 'NRCH Site 2',
        district: 'New Delhi',
        distance: 39,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [76.73884369999999, 27.1671174] },
      properties: {
        center_name: '45 PHC PADA BLOCK RENI',
        district: 'Alwar',
        distance: 212,
        state: 'Rajasthan',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.22224760000002, 28.5237883] },
      properties: {
        center_name: 'Dr. Ambedkar Nagar SectorV DH',
        district: 'South Delhi',
        distance: 30,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.2174596, 28.6365182] },
      properties: {
        center_name: 'Northern Railway Central',
        district: 'New Delhi',
        distance: 39,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.2137944, 28.535326] },
      properties: {
        center_name: 'Pt Madan Mohan Malviya Site 1',
        district: 'South Delhi',
        distance: 29,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.177094, 28.5852879] },
      properties: {
        center_name: 'Charak Palika Hospial Site 1',
        district: 'New Delhi',
        distance: 29,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.1001172, 28.6018934] },
      properties: {
        center_name: 'SKV No. 1 Sagarpur',
        district: 'New Delhi',
        distance: 25,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.1519254, 28.4633209] },
      properties: {
        center_name: 'DGD Jonapur PHC',
        district: 'South Delhi',
        distance: 18,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [76.54704269999999, 27.9207801] },
      properties: {
        center_name: 'GS TODARPUR',
        district: 'Alwar',
        distance: 110,
        state: 'Rajasthan',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.1248931, 28.5984847] },
      properties: {
        center_name: 'Delhi Cantt Gen Hosp. Site 1',
        district: 'New Delhi',
        distance: 26,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.2058155, 28.5680405] },
      properties: {
        center_name: 'Safdrjung Hospital DH S SITE 3',
        district: 'South Delhi',
        distance: 31,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.1891771, 28.5287201] },
      properties: {
        center_name: 'NITRD SITE',
        district: 'South Delhi',
        distance: 26,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [76.31451880000002, 27.4002761] },
      properties: {
        center_name: '45 NAGALBANI THANAGAZI',
        district: 'Alwar',
        distance: 199,
        state: 'Rajasthan',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.2058155, 28.5680405] },
      properties: {
        center_name: 'Safdarjung Hospital DH 2',
        district: 'South Delhi',
        distance: 31,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.22254629999999, 28.5288329] },
      properties: {
        center_name: 'DGD District Court Saket PHC',
        district: 'South Delhi',
        distance: 30,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [76.2899071, 27.2783097] },
      properties: {
        center_name: '45 KISHORI THANAGAZI',
        district: 'Alwar',
        distance: 217,
        state: 'Rajasthan',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [76.31451880000002, 27.4002761] },
      properties: {
        center_name: '45 GUDACHURANI PHC THANAGAZI',
        district: 'Alwar',
        distance: 199,
        state: 'Rajasthan',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [76.1627954, 27.2515793] },
      properties: {
        center_name: '45 CHC PRATAPGARH',
        district: 'Alwar',
        distance: 230,
        state: 'Rajasthan',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [76.3020256, 27.5146608] },
      properties: {
        center_name: '45 CHC NARAYANPUR',
        district: 'Alwar',
        distance: 184,
        state: 'Rajasthan',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [77.2275823, 28.5626799] },
      properties: {
        center_name: 'P. SKV School Fatehpurberi S-2',
        district: 'South Delhi',
        distance: 33,
        state: 'Delhi',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [76.31451880000002, 27.4002761] },
      properties: {
        center_name: '45 KOLAHEDA THANAGAZI',
        district: 'Alwar',
        distance: 199,
        state: 'Rajasthan',
        fee_type: 'Free',
      },
    },
    {
      type: 'Feature',
      geometry: { type: 'Point', coordinates: [76.61249269999999, 27.5634458] },
      properties: {
        center_name: 'District Hospital Covaxin',
        district: 'Alwar',
        distance: 156,
        state: 'Rajasthan',
        fee_type: 'Free',
      },
    },
  ];
